# Generated by Django 4.2.1 on 2023-10-25 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('client_name', models.CharField(max_length=100)),
                ('cpnj', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
                ('cellphone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Salesperson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('cellphone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('cpnj', models.IntegerField()),
                ('service', models.CharField(max_length=100)),
                ('activity', models.CharField(max_length=100)),
                ('nf_process', models.TextField()),
                ('salesperson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='basededados.salesperson')),
            ],
        ),
    ]
