# Generated by Django 4.2.1 on 2023-10-25 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basededados', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distributor',
            name='salesperson',
        ),
        migrations.AddField(
            model_name='salesperson',
            name='distributor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='basededados.distributor'),
        ),
    ]
