# Generated by Django 4.2.1 on 2023-10-25 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basededados', '0002_remove_distributor_salesperson_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributor',
            name='portal',
            field=models.URLField(blank=True, null=True, verbose_name='Portal'),
        ),
        migrations.AlterField(
            model_name='client',
            name='cellphone',
            field=models.IntegerField(verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_name',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='client',
            name='company_name',
            field=models.CharField(max_length=100, verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='activity',
            field=models.CharField(max_length=100, verbose_name='Atividade'),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='company_name',
            field=models.CharField(max_length=100, verbose_name='Distribuidor'),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='nf_process',
            field=models.TextField(verbose_name='Processo para emissão de nota fiscal'),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='service',
            field=models.CharField(max_length=100, verbose_name='Serviço'),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='distributor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='basededados.distributor', verbose_name='Distribuidor'),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
    ]
