# Generated by Django 4.2.1 on 2023-10-25 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basededados', '0003_distributor_portal_alter_client_cellphone_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['client_name'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
    ]
