# Generated by Django 4.2.1 on 2023-10-25 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basededados', '0004_alter_client_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
