# Generated by Django 4.2.1 on 2023-10-25 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basededados', '0005_delete_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, verbose_name='Empresa')),
                ('client_name', models.CharField(max_length=100, verbose_name='Nome')),
                ('cpnj', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
                ('cellphone', models.IntegerField(verbose_name='Telefone')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['client_name'],
            },
        ),
    ]
