# Generated by Django 3.2.10 on 2024-05-28 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basededados', '0008_alter_distributor_activity_alter_distributor_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(upload_to='portfolioapp/images/')),
                ('title', models.CharField(max_length=180)),
                ('demo', models.URLField(blank=True)),
                ('github', models.URLField(blank=True)),
                ('type', models.CharField(choices=[('game', 'game'), ('project', 'project')], default='project', max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.RemoveField(
            model_name='salesperson',
            name='distributor',
        ),
        migrations.DeleteModel(
            name='Distributor',
        ),
        migrations.DeleteModel(
            name='Salesperson',
        ),
    ]
